apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: shop-ecommerce
spec:
  type: LoadBalancer 
  ports:
    - name: api-gateway
      port: 8080  
      targetPort: 8080  
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: kibana
      port: 5601
      targetPort: 5601
  selector:
    network: public   
    