apiVersion: v1
kind: Service
metadata:
  name: node-port
  namespace: shop-ecommerce
spec:
  type: NodePort  
  ports:
    - name: api-gateway
      port: 8080  
      targetPort: 8080  
      nodePort: 30080 
    - name: zipkin
      port: 9411
      targetPort: 9411
      nodePort: 30081
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
      nodePort: 30082
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30083
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30084
    - name: kibana
      port: 5601
      targetPort: 5601
      nodePort: 30085
  selector:
    network: public   
    