apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: shop-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        network: public
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.17
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.shop-ecommerce.svc.cluster.local:9200
