apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: shop-ecommerce
spec:
  selector:
    matchLabels:
      app: product-db  
  replicas: 1
  template:  
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: product-db
          image: mongo:4-focal
          ports: 
            - containerPort: 27017
          volumeMounts: 
            - name: product-db
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongo", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: product-db
          persistentVolumeClaim:
            claimName: product-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: shop-ecommerce
spec:
  type: ClusterIP 
  selector:
    app: product-db  
  ports:
    - port: 27017  
      targetPort: 27017 
