apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service 
  namespace: shop-ecommerce
spec:
  selector:
    matchLabels:
      app: product-service  
  template: 
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: nutcas3/shop-ecommerce-product-service:latest 
          imagePullPolicy: Always 
          ports:
            - containerPort: 8084 
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            limits:
              cpu: "1"  
              memory: "512Mi"
            requests:
              cpu: "600m" 
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shop-ecommerce
spec:
  selector:
    app: product-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP 

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: product-service
  namespace: shop-ecommerce
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 1
  maxReplicas: 10
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75  
